import { useState, useCallback } from 'react';
import { v4 as uuidv4 } from 'uuid';
import { type InvoiceFormData, type InvoiceLineItemFormData } from '../types/invoice-form.types';
import { calculateInvoiceTotals, calculateDueDate } from '../utils/calculateInvoiceTotals';

const createEmptyLineItem = (): InvoiceLineItemFormData => ({
  id: uuidv4(),
  description: '',
  quantity: 1,
  unitPriceMicros: 0,
  currencyCode: 'USD',
  serviceCategory: null,
  sortOrder: 0,
});

const getInitialFormData = (): InvoiceFormData => {
  const today = new Date().toISOString().split('T')[0];
  return {
    companyId: null,
    contactId: null,
    projectId: null,
    quoteId: null,
    invoiceNumber: '', // Auto-generated by backend
    invoiceDate: today,
    dueDate: calculateDueDate(today, 'Net 30'), // Default 30 days
    status: 'DRAFT',
    lineItems: [createEmptyLineItem()],
    discountPercentage: 0,
    taxPercentage: 0,
    amountPaidMicros: 0,
    notes: null,
    paymentTerms: 'Net 30',
    stripeInvoiceId: null,
    stripePaymentLink: null,
  };
};

export const useInvoiceForm = (initialData?: Partial<InvoiceFormData>) => {
  const [formData, setFormData] = useState<InvoiceFormData>(() => ({
    ...getInitialFormData(),
    ...initialData,
  }));
  const [isSaving, setIsSaving] = useState(false);
  const [errors, setErrors] = useState<Record<string, string>>({});

  // Calculate totals whenever form data changes
  const calculations = calculateInvoiceTotals(
    formData.lineItems,
    formData.discountPercentage,
    formData.taxPercentage,
    formData.amountPaidMicros,
  );

  // Update form field
  const updateField = useCallback(
    <K extends keyof InvoiceFormData>(field: K, value: InvoiceFormData[K]) => {
      setFormData((prev) => {
        const updated = { ...prev, [field]: value };

        // Auto-calculate due date when invoice date or payment terms change
        if (field === 'invoiceDate' || field === 'paymentTerms') {
          updated.dueDate = calculateDueDate(
            updated.invoiceDate,
            updated.paymentTerms || 'Net 30',
          );
        }

        return updated;
      });

      // Clear error for this field when user edits
      if (errors[field]) {
        setErrors((prev) => {
          const newErrors = { ...prev };
          delete newErrors[field];
          return newErrors;
        });
      }
    },
    [errors],
  );

  // Add line item
  const addLineItem = useCallback(() => {
    setFormData((prev) => ({
      ...prev,
      lineItems: [
        ...prev.lineItems,
        {
          ...createEmptyLineItem(),
          sortOrder: prev.lineItems.length,
        },
      ],
    }));
  }, []);

  // Update line item
  const updateLineItem = useCallback(
    (index: number, updates: Partial<InvoiceLineItemFormData>) => {
      setFormData((prev) => ({
        ...prev,
        lineItems: prev.lineItems.map((item, i) =>
          i === index ? { ...item, ...updates } : item,
        ),
      }));
    },
    [],
  );

  // Remove line item
  const removeLineItem = useCallback((index: number) => {
    setFormData((prev) => ({
      ...prev,
      lineItems: prev.lineItems.filter((_, i) => i !== index),
    }));
  }, []);

  // Reorder line items
  const reorderLineItems = useCallback(
    (fromIndex: number, toIndex: number) => {
      setFormData((prev) => {
        const items = [...prev.lineItems];
        const [movedItem] = items.splice(fromIndex, 1);
        items.splice(toIndex, 0, movedItem);

        return {
          ...prev,
          lineItems: items.map((item, index) => ({
            ...item,
            sortOrder: index,
          })),
        };
      });
    },
    [],
  );

  // Validate form
  const validate = useCallback((): boolean => {
    const newErrors: Record<string, string> = {};

    if (!formData.companyId) {
      newErrors.companyId = 'Company is required';
    }

    if (!formData.invoiceDate) {
      newErrors.invoiceDate = 'Invoice date is required';
    }

    if (formData.lineItems.length === 0) {
      newErrors.lineItems = 'At least one line item is required';
    }

    // Validate each line item
    formData.lineItems.forEach((item, index) => {
      if (!item.description?.trim()) {
        newErrors[`lineItem.${index}.description`] = 'Description required';
      }
      if (item.quantity <= 0) {
        newErrors[`lineItem.${index}.quantity`] = 'Quantity must be positive';
      }
      if (item.unitPriceMicros < 0) {
        newErrors[`lineItem.${index}.unitPrice`] = 'Price cannot be negative';
      }
    });

    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  }, [formData]);

  // Reset form
  const resetForm = useCallback(() => {
    setFormData(getInitialFormData());
    setErrors({});
    setIsSaving(false);
  }, []);

  return {
    formData,
    calculations,
    errors,
    isSaving,
    setIsSaving,
    updateField,
    addLineItem,
    updateLineItem,
    removeLineItem,
    reorderLineItems,
    validate,
    resetForm,
  };
};
