import * as RadixColors from '@radix-ui/colors';

type AccentSteps = {
  accent1: string;
  accent2: string;
  accent3: string;
  accent4: string;
  accent5: string;
  accent6: string;
  accent7: string;
  accent8: string;
  accent9: string;
  accent10: string;
  accent11: string;
  accent12: string;
};

export type AccentPreset = {
  id: string;
  label: string;
  hex: string;
  light: AccentSteps;
  dark: AccentSteps;
};

export const ACCENT_PRESETS: Record<string, AccentPreset> = {
  indigo: {
    id: 'indigo',
    label: 'Indigo',
    hex: '#3E63DD',
    light: {
      accent1: RadixColors.indigoP3.indigo1,
      accent2: RadixColors.indigoP3.indigo2,
      accent3: RadixColors.indigoP3.indigo3,
      accent4: RadixColors.indigoP3.indigo4,
      accent5: RadixColors.indigoP3.indigo5,
      accent6: RadixColors.indigoP3.indigo6,
      accent7: RadixColors.indigoP3.indigo7,
      accent8: RadixColors.indigoP3.indigo8,
      accent9: RadixColors.indigoP3.indigo9,
      accent10: RadixColors.indigoP3.indigo10,
      accent11: RadixColors.indigoP3.indigo11,
      accent12: RadixColors.indigoP3.indigo12,
    },
    dark: {
      accent1: RadixColors.indigoDarkP3.indigo1,
      accent2: RadixColors.indigoDarkP3.indigo2,
      accent3: RadixColors.indigoDarkP3.indigo3,
      accent4: RadixColors.indigoDarkP3.indigo4,
      accent5: RadixColors.indigoDarkP3.indigo5,
      accent6: RadixColors.indigoDarkP3.indigo6,
      accent7: RadixColors.indigoDarkP3.indigo7,
      accent8: RadixColors.indigoDarkP3.indigo8,
      accent9: RadixColors.indigoDarkP3.indigo9,
      accent10: RadixColors.indigoDarkP3.indigo10,
      accent11: RadixColors.indigoDarkP3.indigo11,
      accent12: RadixColors.indigoDarkP3.indigo12,
    },
  },
  blue: {
    id: 'blue',
    label: 'Blue',
    hex: '#3B9EFF',
    light: {
      accent1: RadixColors.blueP3.blue1,
      accent2: RadixColors.blueP3.blue2,
      accent3: RadixColors.blueP3.blue3,
      accent4: RadixColors.blueP3.blue4,
      accent5: RadixColors.blueP3.blue5,
      accent6: RadixColors.blueP3.blue6,
      accent7: RadixColors.blueP3.blue7,
      accent8: RadixColors.blueP3.blue8,
      accent9: RadixColors.blueP3.blue9,
      accent10: RadixColors.blueP3.blue10,
      accent11: RadixColors.blueP3.blue11,
      accent12: RadixColors.blueP3.blue12,
    },
    dark: {
      accent1: RadixColors.blueDarkP3.blue1,
      accent2: RadixColors.blueDarkP3.blue2,
      accent3: RadixColors.blueDarkP3.blue3,
      accent4: RadixColors.blueDarkP3.blue4,
      accent5: RadixColors.blueDarkP3.blue5,
      accent6: RadixColors.blueDarkP3.blue6,
      accent7: RadixColors.blueDarkP3.blue7,
      accent8: RadixColors.blueDarkP3.blue8,
      accent9: RadixColors.blueDarkP3.blue9,
      accent10: RadixColors.blueDarkP3.blue10,
      accent11: RadixColors.blueDarkP3.blue11,
      accent12: RadixColors.blueDarkP3.blue12,
    },
  },
  violet: {
    id: 'violet',
    label: 'Violet',
    hex: '#6E56CF',
    light: {
      accent1: RadixColors.violetP3.violet1,
      accent2: RadixColors.violetP3.violet2,
      accent3: RadixColors.violetP3.violet3,
      accent4: RadixColors.violetP3.violet4,
      accent5: RadixColors.violetP3.violet5,
      accent6: RadixColors.violetP3.violet6,
      accent7: RadixColors.violetP3.violet7,
      accent8: RadixColors.violetP3.violet8,
      accent9: RadixColors.violetP3.violet9,
      accent10: RadixColors.violetP3.violet10,
      accent11: RadixColors.violetP3.violet11,
      accent12: RadixColors.violetP3.violet12,
    },
    dark: {
      accent1: RadixColors.violetDarkP3.violet1,
      accent2: RadixColors.violetDarkP3.violet2,
      accent3: RadixColors.violetDarkP3.violet3,
      accent4: RadixColors.violetDarkP3.violet4,
      accent5: RadixColors.violetDarkP3.violet5,
      accent6: RadixColors.violetDarkP3.violet6,
      accent7: RadixColors.violetDarkP3.violet7,
      accent8: RadixColors.violetDarkP3.violet8,
      accent9: RadixColors.violetDarkP3.violet9,
      accent10: RadixColors.violetDarkP3.violet10,
      accent11: RadixColors.violetDarkP3.violet11,
      accent12: RadixColors.violetDarkP3.violet12,
    },
  },
  teal: {
    id: 'teal',
    label: 'Teal',
    hex: '#12A594',
    light: {
      accent1: RadixColors.tealP3.teal1,
      accent2: RadixColors.tealP3.teal2,
      accent3: RadixColors.tealP3.teal3,
      accent4: RadixColors.tealP3.teal4,
      accent5: RadixColors.tealP3.teal5,
      accent6: RadixColors.tealP3.teal6,
      accent7: RadixColors.tealP3.teal7,
      accent8: RadixColors.tealP3.teal8,
      accent9: RadixColors.tealP3.teal9,
      accent10: RadixColors.tealP3.teal10,
      accent11: RadixColors.tealP3.teal11,
      accent12: RadixColors.tealP3.teal12,
    },
    dark: {
      accent1: RadixColors.tealDarkP3.teal1,
      accent2: RadixColors.tealDarkP3.teal2,
      accent3: RadixColors.tealDarkP3.teal3,
      accent4: RadixColors.tealDarkP3.teal4,
      accent5: RadixColors.tealDarkP3.teal5,
      accent6: RadixColors.tealDarkP3.teal6,
      accent7: RadixColors.tealDarkP3.teal7,
      accent8: RadixColors.tealDarkP3.teal8,
      accent9: RadixColors.tealDarkP3.teal9,
      accent10: RadixColors.tealDarkP3.teal10,
      accent11: RadixColors.tealDarkP3.teal11,
      accent12: RadixColors.tealDarkP3.teal12,
    },
  },
  green: {
    id: 'green',
    label: 'Green',
    hex: '#30A46C',
    light: {
      accent1: RadixColors.greenP3.green1,
      accent2: RadixColors.greenP3.green2,
      accent3: RadixColors.greenP3.green3,
      accent4: RadixColors.greenP3.green4,
      accent5: RadixColors.greenP3.green5,
      accent6: RadixColors.greenP3.green6,
      accent7: RadixColors.greenP3.green7,
      accent8: RadixColors.greenP3.green8,
      accent9: RadixColors.greenP3.green9,
      accent10: RadixColors.greenP3.green10,
      accent11: RadixColors.greenP3.green11,
      accent12: RadixColors.greenP3.green12,
    },
    dark: {
      accent1: RadixColors.greenDarkP3.green1,
      accent2: RadixColors.greenDarkP3.green2,
      accent3: RadixColors.greenDarkP3.green3,
      accent4: RadixColors.greenDarkP3.green4,
      accent5: RadixColors.greenDarkP3.green5,
      accent6: RadixColors.greenDarkP3.green6,
      accent7: RadixColors.greenDarkP3.green7,
      accent8: RadixColors.greenDarkP3.green8,
      accent9: RadixColors.greenDarkP3.green9,
      accent10: RadixColors.greenDarkP3.green10,
      accent11: RadixColors.greenDarkP3.green11,
      accent12: RadixColors.greenDarkP3.green12,
    },
  },
  orange: {
    id: 'orange',
    label: 'Orange',
    hex: '#F76B15',
    light: {
      accent1: RadixColors.orangeP3.orange1,
      accent2: RadixColors.orangeP3.orange2,
      accent3: RadixColors.orangeP3.orange3,
      accent4: RadixColors.orangeP3.orange4,
      accent5: RadixColors.orangeP3.orange5,
      accent6: RadixColors.orangeP3.orange6,
      accent7: RadixColors.orangeP3.orange7,
      accent8: RadixColors.orangeP3.orange8,
      accent9: RadixColors.orangeP3.orange9,
      accent10: RadixColors.orangeP3.orange10,
      accent11: RadixColors.orangeP3.orange11,
      accent12: RadixColors.orangeP3.orange12,
    },
    dark: {
      accent1: RadixColors.orangeDarkP3.orange1,
      accent2: RadixColors.orangeDarkP3.orange2,
      accent3: RadixColors.orangeDarkP3.orange3,
      accent4: RadixColors.orangeDarkP3.orange4,
      accent5: RadixColors.orangeDarkP3.orange5,
      accent6: RadixColors.orangeDarkP3.orange6,
      accent7: RadixColors.orangeDarkP3.orange7,
      accent8: RadixColors.orangeDarkP3.orange8,
      accent9: RadixColors.orangeDarkP3.orange9,
      accent10: RadixColors.orangeDarkP3.orange10,
      accent11: RadixColors.orangeDarkP3.orange11,
      accent12: RadixColors.orangeDarkP3.orange12,
    },
  },
  rose: {
    id: 'rose',
    label: 'Rose',
    hex: '#D6409F',
    light: {
      accent1: RadixColors.pinkP3.pink1,
      accent2: RadixColors.pinkP3.pink2,
      accent3: RadixColors.pinkP3.pink3,
      accent4: RadixColors.pinkP3.pink4,
      accent5: RadixColors.pinkP3.pink5,
      accent6: RadixColors.pinkP3.pink6,
      accent7: RadixColors.pinkP3.pink7,
      accent8: RadixColors.pinkP3.pink8,
      accent9: RadixColors.pinkP3.pink9,
      accent10: RadixColors.pinkP3.pink10,
      accent11: RadixColors.pinkP3.pink11,
      accent12: RadixColors.pinkP3.pink12,
    },
    dark: {
      accent1: RadixColors.pinkDarkP3.pink1,
      accent2: RadixColors.pinkDarkP3.pink2,
      accent3: RadixColors.pinkDarkP3.pink3,
      accent4: RadixColors.pinkDarkP3.pink4,
      accent5: RadixColors.pinkDarkP3.pink5,
      accent6: RadixColors.pinkDarkP3.pink6,
      accent7: RadixColors.pinkDarkP3.pink7,
      accent8: RadixColors.pinkDarkP3.pink8,
      accent9: RadixColors.pinkDarkP3.pink9,
      accent10: RadixColors.pinkDarkP3.pink10,
      accent11: RadixColors.pinkDarkP3.pink11,
      accent12: RadixColors.pinkDarkP3.pink12,
    },
  },
  slate: {
    id: 'slate',
    label: 'Slate',
    hex: '#889096',
    light: {
      accent1: RadixColors.slateP3.slate1,
      accent2: RadixColors.slateP3.slate2,
      accent3: RadixColors.slateP3.slate3,
      accent4: RadixColors.slateP3.slate4,
      accent5: RadixColors.slateP3.slate5,
      accent6: RadixColors.slateP3.slate6,
      accent7: RadixColors.slateP3.slate7,
      accent8: RadixColors.slateP3.slate8,
      accent9: RadixColors.slateP3.slate9,
      accent10: RadixColors.slateP3.slate10,
      accent11: RadixColors.slateP3.slate11,
      accent12: RadixColors.slateP3.slate12,
    },
    dark: {
      accent1: RadixColors.slateDarkP3.slate1,
      accent2: RadixColors.slateDarkP3.slate2,
      accent3: RadixColors.slateDarkP3.slate3,
      accent4: RadixColors.slateDarkP3.slate4,
      accent5: RadixColors.slateDarkP3.slate5,
      accent6: RadixColors.slateDarkP3.slate6,
      accent7: RadixColors.slateDarkP3.slate7,
      accent8: RadixColors.slateDarkP3.slate8,
      accent9: RadixColors.slateDarkP3.slate9,
      accent10: RadixColors.slateDarkP3.slate10,
      accent11: RadixColors.slateDarkP3.slate11,
      accent12: RadixColors.slateDarkP3.slate12,
    },
  },
};

export const DEFAULT_ACCENT_PRESET_ID = 'indigo';
