import { useState, useCallback } from 'react';
import { v4 as uuidv4 } from 'uuid';
import {
  type QuoteFormData,
  type QuoteLineItemFormData,
} from '../types/quote-form.types';
import { calculateQuoteTotals } from '../utils/calculateQuoteTotals';

const createEmptyLineItem = (): QuoteLineItemFormData => ({
  id: uuidv4(),
  description: '',
  quantity: 1,
  unitPriceMicros: 0,
  currencyCode: 'USD',
  serviceCategory: null,
  sortOrder: 0,
});

const getInitialFormData = (): QuoteFormData => ({
  companyId: null,
  contactId: null,
  projectId: null,
  quoteNumber: '', // Will be auto-generated by backend
  quoteDate: new Date().toISOString().split('T')[0], // Today
  expirationDate: null,
  status: 'DRAFT',
  lineItems: [createEmptyLineItem()],
  discountPercentage: 0,
  taxPercentage: 0,
  notes: null,
  terms: null,
});

export const useQuoteForm = () => {
  const [formData, setFormData] = useState<QuoteFormData>(getInitialFormData());
  const [isSaving, setIsSaving] = useState(false);
  const [errors, setErrors] = useState<Record<string, string>>({});

  // Calculate totals whenever form data changes
  const calculations = calculateQuoteTotals(
    formData.lineItems,
    formData.discountPercentage,
    formData.taxPercentage,
  );

  // Update form field
  const updateField = useCallback(
    <K extends keyof QuoteFormData>(field: K, value: QuoteFormData[K]) => {
      setFormData((prev) => ({ ...prev, [field]: value }));
      // Clear error for this field when user edits
      if (errors[field]) {
        setErrors((prev) => {
          const newErrors = { ...prev };
          delete newErrors[field];
          return newErrors;
        });
      }
    },
    [errors],
  );

  // Add line item
  const addLineItem = useCallback(() => {
    setFormData((prev) => ({
      ...prev,
      lineItems: [
        ...prev.lineItems,
        {
          ...createEmptyLineItem(),
          sortOrder: prev.lineItems.length,
        },
      ],
    }));
  }, []);

  // Update line item
  const updateLineItem = useCallback(
    (index: number, updates: Partial<QuoteLineItemFormData>) => {
      setFormData((prev) => ({
        ...prev,
        lineItems: prev.lineItems.map((item, i) =>
          i === index ? { ...item, ...updates } : item,
        ),
      }));
    },
    [],
  );

  // Remove line item
  const removeLineItem = useCallback((index: number) => {
    setFormData((prev) => ({
      ...prev,
      lineItems: prev.lineItems.filter((_, i) => i !== index),
    }));
  }, []);

  // Reorder line items (for drag-and-drop)
  const reorderLineItems = useCallback((fromIndex: number, toIndex: number) => {
    setFormData((prev) => {
      const items = [...prev.lineItems];
      const [movedItem] = items.splice(fromIndex, 1);
      items.splice(toIndex, 0, movedItem);

      // Update sortOrder
      return {
        ...prev,
        lineItems: items.map((item, index) => ({
          ...item,
          sortOrder: index,
        })),
      };
    });
  }, []);

  // Validate form
  const validate = useCallback((): boolean => {
    const newErrors: Record<string, string> = {};

    if (!formData.companyId) {
      newErrors.companyId = 'Company is required';
    }

    if (!formData.quoteDate) {
      newErrors.quoteDate = 'Quote date is required';
    }

    if (formData.lineItems.length === 0) {
      newErrors.lineItems = 'At least one line item is required';
    }

    // Validate each line item
    formData.lineItems.forEach((item, index) => {
      if (!item.description?.trim()) {
        newErrors[`lineItem.${index}.description`] = 'Description required';
      }
      if (item.quantity <= 0) {
        newErrors[`lineItem.${index}.quantity`] = 'Quantity must be positive';
      }
      if (item.unitPriceMicros < 0) {
        newErrors[`lineItem.${index}.unitPrice`] = 'Price cannot be negative';
      }
    });

    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  }, [formData]);

  // Reset form
  const resetForm = useCallback(() => {
    setFormData(getInitialFormData());
    setErrors({});
    setIsSaving(false);
  }, []);

  return {
    formData,
    calculations,
    errors,
    isSaving,
    setIsSaving,
    updateField,
    addLineItem,
    updateLineItem,
    removeLineItem,
    reorderLineItems,
    validate,
    resetForm,
  };
};
